### PR TITLE
Update to angular 15

### PR DESCRIPTION
**Pull request by Anthony-Wratpor**
Hello,
Could you merge this for angular 15 compatibilities please ? 
i'm fairly new to pull requests but i've updated this pacakge to Angular 15 (based on how other users updated to angular 14 and 13), so be sure to check it thoroughly before merging ! 

Thanks in advance !

### CODE REVIEW

**Comment by tofiqquadri** [comment]
> Hello, Could you merge this for angular 15 compatibilities please ? i'm fairly new to pull requests but i've updated this pacakge to Angular 15 (based on how other users updated to angular 14 and 13), so be sure to check it thoroughly before merging !
> 
> Thanks in advance !

Give me today's time to check and merge. Thanks for the efforts

**Comment by aryngaladar** [comment]
Any update on adding the Angular 15 compatibility?

**Comment by maxailloud** [comment]
Any news about this PR? @tofiqquadri

**Comment by tofiqquadri** [comment]
@maxailloud @aryngaladar @Anthony-Wratpor ngx-csv-parser has been updated to support Angular 15

**Comment by maxailloud** [comment]
Thank you @tofiqquadri.

**Pull request closed without merging**
