### PR TITLE
Added support for Angular 16

### PR DESCRIPTION
**Pull request by felhag**

### CODE REVIEW

**Comment by anikets43** [comment]
@tofiqquadri @felhag Could you please review and merge this

**Comment by tofiqquadri** [comment]
@anikets43 I'll finish this by today or tomorrow.

**Comment by srpulga** [comment]
@tofiqquadri any updates ? I need to update my angular to 16

**Comment by tofiqquadri** [comment]
@srpulga 3 Hours more to go, sorry to keep you guys waiting.

**Comment by tofiqquadri** [comment]
@srpulga @anikets43 check latest version of ngx-csv-parser 1.3.1 It should support Angular 16 perfectly fine, Create an issue if it doesn't.

**Comment by srpulga** [comment]
all good, thank's @tofiqquadri 🥳

**Pull request closed without merging**
