### PR TITLE
chore: update to angular 14

### PR DESCRIPTION
**Pull request by anikets43**
Ran: `ng update @angular/core@14 @angular/cli@14`

### CODE REVIEW

**Comment by anikets43** [comment]
@tofiqquadri Can we get this merged?

**Comment by tofiqquadri** [comment]
@anikets43 that would be awesome! I'll do it tomorrow.

**Comment by anikets43** [comment]
@tofiqquadri Do we have any blocker to get this PR merged? Please let me know if I could do anything from my end

**Comment by abhinav2000kiit** [comment]
@tofiqquadri Bump on this

**Pull request closed without merging**
